{application,adder,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{adder_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[adder,adder_app,adder_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
